name: C/C++

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: installation
      run: sudo apt install -y googletest libgtest-dev build-essential
    - name: installation mpi
      run: |
        sudo apt-get update
        sudo apt-get install -y mpich
    - name: Компиляция модульных тестируемых
      run: |
        
        make test
    - name: start tests
      run: ./main

    - name: compile debug
      run: |
        mpic++ -o test test.cpp
        mpirun -np 20 ./test